# Data
path: your_training_set_images_path # 01_annotating/01_annotated_files
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [4, 3]  # [number of keypoints, number of dim]

# Classes
names:
  0: jackdaw
